### PR TITLE
Dynamic memory allocation

### PR DESCRIPTION
**Pull request by israelferrazaraujo**
Dynamic allocation enables a more rational memory use by allocating just what is necessary for a given resource. It also allows a trade-off between responsiveness and memory usage.

On **HUBG**, it is applied only to package details but can be used for any data structure.

The size of the memory region for dynamic allocation is set to `DYNAMIC_MEM_SIZE 2048` (2kB) in **HUBG.h** file. The function responsible for the memory allocation is `Malloc` in **HUBG.c** (probably will migrate to a library).

### CODE REVIEW

**Comment by israelferrazaraujo** [comment]
The application is now tested.

Most of the changes are in the functions:
- `GroupListRcvCallBack`
- `SearchListRcvCallBack`
- `GetPackageDetail`
- `Malloc`
- `Free`

The version number still needs to be updated.

**Comment by ducasp** [comment]
@israelferrazaraujo 
Thanks for your work, I've been a little bit busy with some FPGA related stuff, should get back to evaluate it properly in a few days.

**Review by ducasp — CHANGES_REQUESTED** [review]
First of all, thanks for this pull request. It is a great new feature to have a dynamic cache of descriptions and allowing the count of packages to go up... This is a mid-term solution (a long term solution probably will need to be different, MSX DEV is adding 20-30 games every year) and I really liked the way you did, keep everything fast and getting data from a category only once before listing.

On the other hand, I would like some changes before merging your update:

1. Make sure to update the header of the files you've changed. I propose to bump the version from 0.80 to 0.90, add - 2022 after 2020 in the copyright and below it add a line with your name or nickname and description of your contribution (i.e.: -- Israel Ferraz Araujo: contribution to expand the number of packages in a category that can be listed)

2. ucSWInfoANSI: update the version, year to 2020, add your name (and if you wish, e-mail, github, etc) before mine as this version is yours (so \r\n (c) 2022 Israel.... \r\n Oduvaldo)

3. Change HUBGmenus.h, header version can bump to 0.2 and  change second line of chHubGMenu to have version 0.90 and your nick there (i.e.: IFA / DucaSP). If needed, you can remove my e-mail address from there.

4. Nice to have: I would like to have the names changed from Malloc and Free to something that reflects this is a cache ( AllocCache / ClearCache would be my suggestion) as this makes a lot esier to get whoever is looking at the code to not think of malloc and free standard implementation. While at it, you can add the declaration on HUBG.h header file so you do not need to declare Free/ClearCache in the C file. :)

5. Line 818 of HUBG.c, I would keep the check if n is lesser than bytes_read instead of setting rcv_buffer[bytes_read] to 0 and checking if it is null... If for some reason data contains null (which is not nice but could happen) the remaining data will be ignored, also, rcv_buffer is not owned by HUBG.c, so there are no guarantees that we can write on what is on front of rcv_buffer[bytes_read] as rcv_buffer capacity could have been fully used. It works nice at this moment because hget lib put that buffer as the last in the mem area it receives the address to use in INIT, but might cause issues if it is updated in a future date moving the place where the written data is saved on the mem area in a different region, as if that happens, writing 0 at the position just after the buffer size indicated might write that 0 in another area of memory being used for something else. 

6. Please add the COM file you generate on BINARY_PACK\HUBG.ZIP, also update BINARY_PACK\README.MD accordingly with the new version and description of changes and crediting yourself as well :)

**Comment by ducasp** [comment]
Hi @israelferrazaraujo 
Sorry for taking long to review this, it got totally forgotten and you could have asked me about it, sometimes real life takes over and we end-up forgetting what is pending, really sorry, should have some time by the end of this week but I saw it was closed / deleted, hope it is not lost, is it? Sorry again about forgetting it, it is a great addition and should have already been released :(

**Comment by ducasp** [comment]
@israelferrazaraujo Just to let you know, I was able to test it this morning and all is working fine, amazed it is able to list all 132 packages in game categories so far, we will most likely bump into some limitation in the future, but this is a clever and quick solution for the time being, thanks again for your hard work, I've released it on my repository and I've made a request to update MSXHUB HUB package with it as well.

**Comment by ducasp** [comment]
@israelferrazaraujo , HUBG has been oficially updated on msxhub.com and on msxhub servers, again, thanks for your help! :)

**Comment by israelferrazaraujo** [comment]
Hey @ducasp ,

It's nice to have this opportunity to contribute to your great work.
Thanks!

I hope to contribute more soon.

Kind regards!

**Pull request merged**
